#!/bin/bash
set -e


#preliminaries
cd ../..
mkdir /usr/local/games
mv IndieStudio /usr/local/games
cd /usr/local/games/IndieStudio/Install

#dependancies

cd ogre_build-master
./install_dependencies.sh
git clone https://github.com/OGRECave/ogre
./build.sh
cd ogre
git checkout v1-9
mkdir build && cd build
cmake ..
make -j2
sudo make install
cd ../../../

sudo apt-get install libbullet-dev
sudo apt-get install libbullet-extras-dev
git clone https://bitbucket.org/alexeyknyshev/ogrebullet.git
cd ogrebullet
cmake .
sudo make install
cd ../

sudo apt-get --reinstall install mercurial mercurial-common
sudo apt-get -y install build-essential automake libtool
sudo apt-get -y install libfreetype6-dev libfreeimage-dev libzzip-dev
sudo apt-get -y install libxrandr-dev libxaw7-dev freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev
sudo apt-get -y install nvidia-cg-toolkit libois-dev libboost-thread-dev libboost-all-dev
sudo apt-get -y install cmake cmake-gui
sudo apt-get -y install build-essential libiconv-hook-dev libfribidi-dev
sudo apt-get -y install libpcre3-dev libfreetype6-dev freeglut3-dev libpython-dev
sudo apt-get -y install libglew-dev libglm-dev libois-dev libxml2-dev python-opengl pyside-tools libboost-python-dev libboost-dev -y
sudo apt-get -y install libcpprest-dev
hg clone https://bitbucket.org/cegui/cegui
cd cegui && hg update v0-8 && hg checkout 75b9fcc4e3cb
mkdir build && cd build
cmake -DCEGUI_BUILD_PYTHON_MODULES=ON -DCEGUI_BUILD_RENDERER_OPENGL=ON -DCEGUI_BUILD_RENDERER_OPENGL3=ON .-DCEGUI_BUILD_RENDERER_OGRE=ON ../
make -j4
sudo make install

sudo apt-get install libsfml-dev

sudo apt-get install libois-dev


#compiling

cd /usr/local/games/IndieStudio
mkdir build
cd build
cmake ..
make -j4
cp Indie /usr/local/bin/Gauntlet
echo "Gauntlet has been installed with success, type 'Gauntlet' from command-line to play\n"
