#!/bin/bash

mkdir /usr/local/games
cd /usr/local/games
git clone https://github.com/myriamcholetEpitech/IndieStudio.git
cd IndieStudio/Install
echo "Preliminary install was successful, please run install_indie in order to install the game\n"
