#!/bin/bash

directory="/usr/local/games"

set -e

if [ ! -d $directory ]; then
    mkdir $directory
fi

cd /usr/local/games
sudo git clone https://github.com/myriamcholetEpitech/IndieStudio.git
cd IndieStudio/Install
echo -e "\033[32m Preliminary install was successful, please run install_indie (in /usr/local/games/IndieSudio/Install/) in order to install the game\n\e[0m"
