#!/bin/bash

directory="/usr/local/games"

set -e

if [ ! -d $directory ]; then
    mkdir $directory
fi

cd /usr/local/games
sudo git clone https://github.com/myriamcholetEpitech/IndieStudio.git
cd IndieStudio/Install
echo -e "Preliminary install was successful, please run install_indie in order to install the game\n"
